site_name: Loot Price documentation
repo_url: https://github.com/CODEbugging3000/lootprice

theme: 
  name: material
  
  palette:
    
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: green
      accent: yellow
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.instant
    - navigation.footer

  logo: assets/lootpriceicon.png
  
  favicon: assets/favicon.ico

nav:
  - Home: index.md
  - API: api.md
  - DataBase: database.md
  - Scraping: scraping.md
  - Deploy: deploy.md
  - Contributing: contributing.md
  - Price Tracker: price_tracker.md

# markdown_extensions:
#   - pymdownx.superfences:  # For diagrams
#       custom_fences:
#         - name: mermaid
#           class: mermaid
#           format: !!python/name:pymdownx.superfences.fence_code_format

# extra_css:
# - stylesheets/extra.css

extra:
  copyright: Copyright &copy; 2025 CODEbugging3000
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CODEbugging3000/lootprice
    - icon: fontawesome/solid/envelope
      link: mailto:g.alvesdearaujo06@gmail.com